### PR TITLE
Reduce POD warnings and errors

### PR DESCRIPTION
**Pull request by paultcochrane**
These changes fix all errors and most warnings thrown by `podchecker`.

Comments and feedback are most certainly welcome.

### CODE REVIEW

**Comment by ribasushi** [comment]
Any chance of following this with an `xt/pod.t` test, so that a PR like this is never needed again? If in doubt - steal the one from DBIC.

Thanks!

**Comment by paultcochrane** [comment]
Sure, no worries!  I've got a couple of other ideas which would probably fit well with such a test, so let's keep this PR on ice until I've gotten the other code written.

**Comment by ribasushi** [comment]
@paultcochrane In the meantime I have applied 94cbc3d, 4646fca and 5f8797a
as 
33d693c3, f60d4c6c and 0e9badbf respectively.

The remaining 2 commits in this PR will stay on ice until you get back to this.

**Comment by ribasushi** [comment]
As per short IRC conversation this PR will be closed with no further action. The outstanding work is resolved as follows:
c6d070f - The slashes within `L<>` headings will **not** be converted to `E<>` sequences. A future xt/ test will make steps to explicitly ignore this warnings as it is of no practical consequence.
eef0c99 - Seems like a botched partial commit, will be resubmitted as a separate PR

**Comment by ribasushi** [comment]
@paultcochrane let me know if I missed something ;)

**Comment by paultcochrane** [comment]
@ribasushi looks good :-)

**Pull request closed without merging**
