### PR TITLE
Backward-compatible sqlite autoincrement

### PR DESCRIPTION
**Pull request by basiliscos**
Hello, 

Here is another attempt to introduce sqlite monotonic autoincrement which tries to be back-compatible.

Without extending ```SQL::Translator::Schema::Field``` I decided to use ```extra``` field to store type of autoincrement, which later could be re-used from Producer.

I hope this would be OK.

I tried to use it directly in ```DBIx::Class``` :

```perl

{ data_type => "integer", is_auto_increment => 1, is_nullable => 0, extra => { autoinc_method => 'sequence' } }

```

- it works that way. But how to specify extra more correctly in DBIx::Class? i..e outside of auto-generated sources?

Thanks for the great project!

### CODE REVIEW

**Comment by basiliscos** [comment]
OK, I have renamed **auto_increment_method** in extra field. 

Should I enhance ```SQL::Translator::Parser::SQLite``` too, as described above?  I ask that because it seems to be breaking compatibilty?

**Comment by basiliscos** [comment]
Indeed. Thanks for noting that.

**Comment by ribasushi** [comment]
Hi, just looked over this in depth.

The patch itself is good, naming not so much. Would you be opposed to the following changes:
`auto_increment_method` => `auto_increment_type`
and `sequence` => `monotonic`

**Comment by ribasushi** [comment]
Applied with proposed changes as 7f3f64d75. Thank you!

**Comment by karupanerura** [comment]
Great :+1:!
I need it. When it release to CPAN?

**Comment by ribasushi** [comment]
On 10/12/2015 08:34 AM, karupanerura wrote:
>
> Great :+1:!
> I need it. When it release to CPAN?
>
>

In about another week. Sorry for the delay with this :/

**Pull request closed without merging**
