### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by dmorozov001**
Added readme based on https://sqlfairy.sourceforge.net/. This will help new contributors to get familiar with the project

### CODE REVIEW

**Comment by dmorozov001** [comment]
Kindly requesting review @rabbiveesh

**Comment by rabbiveesh** [comment]
Wow, thanks so much for contributing!

Unfortunately, that info is horribly outdated, and does not represent where the project currently stands.

perhaps you could try converting from the current main POD document to a README? Most perl projects are doing that nowadays.

**Comment by dmorozov001** [comment]
Thank you for your feedback. Will do

**Comment by rabbiveesh** [comment]
Hi, i would've rather you force pushed the updates to this PR rather than opening a new one, but whatever

**Pull request closed without merging**
