### PR TITLE
implemented materialized views for pg

### PR DESCRIPTION
**Pull request by rabbiveesh**
This is a beginning implementation of materialized view for PG.

I assume this sort of contribution is wanted.
What do you think, the docs say you can't make a temporary materialized view. So should this mean that the materialized view should be created and it'll drop the temporary, it should only do temporary and not materialized, or die a horrible death?

### CODE REVIEW

**Comment by abraxxa** [comment]
See also Oracle materialized view support in 8d59dd515dae2a6d6dd50da7aa7eb2367042e8e8 which allows to specify options.

**Comment by rabbiveesh** [comment]
as per https://www.postgresql.org/docs/10/sql-creatematerializedview.html there aren't any materialized-view specific options, just a slightly limited set of table options.

**Comment by abraxxa** [comment]
Being able to specify the WITH parameter would make sense.

**Comment by rabbiveesh** [comment]
it's a subset of what's available on table creation. It doesn't seem like
there's an interface for that on tables either, so I don't think it would
affect this PR.

It's different than Oracle, which has options in the with clause that
affect deployment of the view, these things in the with clause are about
the table in general.

**Comment by mohawk2** [comment]
Looks good to me. I do worry about all the `extra` things, they might want making official.

**Review by mohawk2 — APPROVED** [review]

**Pull request merged**
