### PR TITLE
Patch bin scripts to support the #! Makefile.PL was invoked with

### PR DESCRIPTION
**Pull request by toddr**
setting it to /usr/bin/perl makes EUMM update the #! during install

### CODE REVIEW

**Comment by abraxxa** [comment]
Which breaks building in a different path than deploying to.
-1 from me

**Comment by toddr** [comment]
I'll give you a real work example. Let's say you install SQL::Translator to your perl in /usr/local. The assumption is that if I run /usr/local/bin/sqlt-diff, it'll work. However if my $PATH is set to pick perl out of /usr/bin first, then the script will fail because SQL::Translator was not installed to that perl.

So you want ExtUtils::MakeMaker to update the #! of all of the scripts during make install to point to the path of the perl they were installed to. It will not do this unless your #! is /usr/bin/perl in cpan distro.

https://metacpan.org/pod/ExtUtils::MakeMaker#EXE_FILES

**Comment by abraxxa** [comment]
I know that behaviour and it annoys me very much. We build our Perls using `-Duserelocatableinc` and EUMM breaks that when deployed to a different directory on the producation boxes than on the build host.

**Comment by toddr** [comment]
@abraxxa BTW, this discussion is ongoing at: https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/issues/58

**Comment by rabbiveesh** [comment]
Im hoping to do a release soon, and would like to merge easy issues to help give the impression that there'll be active maintenance.

I think that changing the shebangs is the right thing, but discussion on IRC has led me to believe that `#!perl` is the best option. That way you can't accidentally run it on the wrong perl during development (a problem that I have stumbled on more than once).

Any objections?

**Comment by abraxxa** [comment]
As said before that breaks relocateable Perls where the `perl` binary is in a different directory at install time vs. at runtime.
So I'm against merging this.

**Comment by Grinnz** [comment]
In my opinion, breaking in standard installations is more critical than breaking in relocatable installations, which is why the shebang fix is utilized by nearly all CPAN scripts. Clearly it is not a perfect fix (and the referenced EUMM issue stalled out before anyone did the work) but relocatable installations are very much an advanced usage of perl and such users will need to deal with this issue regardless - I don't think it's appropriate to require the vast majority of users to also deal with it.

**Comment by toddr** [comment]
I've updated the PR to match your decision. This also solves my problem.

**Comment by rabbiveesh** [comment]
sorry for the delay, thanks for the PR!

**Pull request merged**
